#!/usr/bin/bash

# Requires MTOOLS To Build Floppy Image.
# Requires DJGPP To Compile Runtime Program.
# Requires QuicBuild (Via MabelHUB), Cargo/RustLang & MinGW-64 To Compile host Program.

rm -r Release
QuicBuild Host x86_64-pc-windows-gnu $@
. /usr/local/djgpp/setenv
cp Static/* Release
g++ Runtime/src/*.cc -o Release/Runtime.exe -O3 -fomit-frame-pointer -fno-exceptions
strip Release/Runtime.exe
upx --best --lzma Release/Runtime.exe
dd if=/dev/zero of=Release/Floppy.img bs=512 count=2880
mformat -i Release/Floppy.img
mcopy -i Release/Floppy.img Release/Runtime.exe ::/RUNTIME.EXE