[package]
name = "Host"
version = "0.0.0"
edition = "2024"
authors = [ "MabelMedia LLC" ]

[dependencies]
byteorder = "*"
whoami = "*"

[profile.release]
debug = 0
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"